# Generated by Django 4.2.1 on 2023-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='github_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forms',
            name='linkedin_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forms',
            name='accepting_responses',
            field=models.BooleanField(default=True),
        ),
    ]
