# Generated by Django 4.2.1 on 2023-08-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forms', '0002_forms_github_required_forms_linkedin_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='group_allowed',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
