# Generated by Django 4.2.1 on 2023-07-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_forms_fields_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('shortlisted', 'Shortlisted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=200),
        ),
    ]
